# Netlify Configuration

# Redirects - PÃ¡ginas de clases
[[redirects]]
  from = "/es/clases"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/es/clases/"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/es/clases/kimono"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/es/clases/kimono/"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/es/clases/grappling"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/es/clases/grappling/"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/es/clases/particulares"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/es/clases/particulares/"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/es/clases/jiu-jitsu-infantil"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/es/clases/jiu-jitsu-infantil/"
  to = "/"
  status = 301
  force = true
